package com.jakirbd.inventory_management.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

public class CategoryCreateRequest {

	//Since you're using Spring Boot 3 + Java 21 + Jakarta Validation, your request DTO should contain only the fields that the client is allowed to send.
	// It should not include database-generated fields like categoryId, status, createdAt, or updatedAt.
	@NotBlank(message = "Category name is required.")
	@Size(max = 100, message = "Category name must not exceed 100 characters.")
	private String categoryName;

	@Size(max = 500, message = "Description must not exceed 500 characters.")
	private String description;

	public CategoryCreateRequest() {
	}

	public String getCategoryName() {
		return categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Override
	public String toString() {
		return String.format(
			"CategoryCreateRequest{categoryName='%s', description='%s'}",
			categoryName,
			description
		);
	}
}

// Why only these two fields?

// CATEGORY_PKG.ADD_CATEGORY(
//     p_category_name,
//     p_description,
//     p_category_id OUT
// );

// And your table definition
// category_id   -> Generated by Identity
// status        -> Default 'ACTIVE'
// created_at    -> Default SYSTIMESTAMP
// updated_at    -> NULL initially

// So the client only needs to provide:
// {
//   "categoryName": "Electronics",
//   "description": "Electronic products"
// }

// Everything else is managed by Oracle.
