-- =======================================================
-- 1. Master Tables
-- =======================================================

-----------------------------------------------------------
-- Create Categories Table
-----------------------------------------------------------
CREATE TABLE categories (
    category_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    category_name   VARCHAR2(100) NOT NULL,
    description     VARCHAR2(500),
    status          VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at      TIMESTAMP,
	 CONSTRAINT PK_Categories	PRIMARY KEY(category_id),
     CONSTRAINT UK_Categories_Name UNIQUE (category_name),
	 CONSTRAINT CHK_Categories_Status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-----------------------------------------------------------
-- Create Suppliers Table
-----------------------------------------------------------
CREATE TABLE suppliers (
    supplier_id     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    supplier_name   VARCHAR2(150) NOT NULL,
    contact_person  VARCHAR2(100),
    phone           VARCHAR2(30),
    email           VARCHAR2(150),
    address         VARCHAR2(500),
    status          VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at      TIMESTAMP,
	 CONSTRAINT PK_Supplier PRIMARY KEY(supplier_id),
	 CONSTRAINT UK_Supplier_Phone UNIQUE(phone),
	 CONSTRAINT UK_Supplier_Email UNIQUE(email),
	 CONSTRAINT CHK_Suppliers_Status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-----------------------------------------------------------
-- Create Buyers Table
-----------------------------------------------------------
CREATE TABLE buyers (
    buyer_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    buyer_name      VARCHAR2(150) NOT NULL,
    contact_person  VARCHAR2(100),
    phone           VARCHAR2(30),
    email           VARCHAR2(150),
    address         VARCHAR2(500),
    status          VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at      TIMESTAMP,

    CONSTRAINT PK_Buyers PRIMARY KEY (buyer_id),
    CONSTRAINT UK_Buyers_Phone UNIQUE (phone),
    CONSTRAINT UK_Buyers_Email UNIQUE (email),
    CONSTRAINT CHK_Buyers_Status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-----------------------------------------------------------
-- Create Warehouses Table
-----------------------------------------------------------
CREATE TABLE warehouses (
    warehouse_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    warehouse_name  VARCHAR2(150) NOT NULL,
    location        VARCHAR2(300),
    status          VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at      TIMESTAMP,

    CONSTRAINT PK_Warehouses PRIMARY KEY (warehouse_id),
    CONSTRAINT UK_Warehouses_Name UNIQUE (warehouse_name),
    CONSTRAINT CHK_Warehouses_Status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- =======================================================
-- 2. Product Management
-- =======================================================
-----------------------------------------------------------
-- Create Products Table
-----------------------------------------------------------
CREATE TABLE products (
    product_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    category_id     NUMBER NOT NULL,
    product_code    VARCHAR2(50) NOT NULL,
    product_name    VARCHAR2(150) NOT NULL,
    unit_price      NUMBER(12,2) DEFAULT 0 NOT NULL,
    reorder_level   NUMBER DEFAULT 0 NOT NULL,
    status          VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at      TIMESTAMP,
	 CONSTRAINT PK_Products PRIMARY KEY(product_id),
    CONSTRAINT UK_Products_Code UNIQUE (product_code),
    CONSTRAINT FK_Products_Category
        FOREIGN KEY (category_id)
        REFERENCES categories(category_id),
	 CONSTRAINT CHK_Products_Status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-----------------------------------------------------------
-- Create Product Suppliers Table
-----------------------------------------------------------
CREATE TABLE product_suppliers (
    product_supplier_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    product_id          NUMBER NOT NULL,
    supplier_id         NUMBER NOT NULL,
    supplier_price      NUMBER(12,2) DEFAULT 0 NOT NULL,
    lead_time_days      NUMBER DEFAULT 0,
    is_primary_supplier VARCHAR2(1) DEFAULT 'N' NOT NULL,
    status              VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at          TIMESTAMP,

    CONSTRAINT PK_Product_Suppliers PRIMARY KEY (product_supplier_id),

    CONSTRAINT FK_PS_Product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id),

    CONSTRAINT FK_PS_Supplier
        FOREIGN KEY (supplier_id)
        REFERENCES suppliers(supplier_id),

    CONSTRAINT UK_PS_Product_Supplier
        UNIQUE (product_id, supplier_id),

    CONSTRAINT CHK_PS_Primary_Supplier
        CHECK (is_primary_supplier IN ('Y', 'N')),

    CONSTRAINT CHK_PS_Status
        CHECK (status IN ('ACTIVE', 'INACTIVE')),

    CONSTRAINT CHK_PS_Supplier_Price
        CHECK (supplier_price >= 0),

    CONSTRAINT CHK_PS_Lead_Time
        CHECK (lead_time_days >= 0)
);

-- =======================================================
-- 3. Inventory Management
-- =======================================================

-----------------------------------------------------------
-- Create Stock Table
-----------------------------------------------------------
CREATE TABLE stock (
    stock_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    product_id     NUMBER NOT NULL,
    warehouse_id   NUMBER NOT NULL,
    quantity       NUMBER DEFAULT 0 NOT NULL,
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at     TIMESTAMP,

    CONSTRAINT PK_Stock PRIMARY KEY (stock_id),

    CONSTRAINT FK_Stock_Product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id),

    CONSTRAINT FK_Stock_Warehouse
        FOREIGN KEY (warehouse_id)
        REFERENCES warehouses(warehouse_id),

    CONSTRAINT UK_Stock_Product_Warehouse
        UNIQUE (product_id, warehouse_id),

    CONSTRAINT CHK_Stock_Quantity
        CHECK (quantity >= 0)
);

-----------------------------------------------------------
-- Create Stock Transactions Table
-----------------------------------------------------------
CREATE TABLE stock_transactions (
    transaction_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    product_id          NUMBER NOT NULL,
    warehouse_id        NUMBER NOT NULL,
    transaction_type    VARCHAR2(20) NOT NULL,
    quantity            NUMBER NOT NULL,
    transaction_date    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    reference_no        VARCHAR2(100),
    remarks             VARCHAR2(500),
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_Stock_Transactions PRIMARY KEY (transaction_id),

    CONSTRAINT FK_ST_Product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id),

    CONSTRAINT FK_ST_Warehouse
        FOREIGN KEY (warehouse_id)
        REFERENCES warehouses(warehouse_id),

    CONSTRAINT CHK_ST_Quantity
        CHECK (quantity > 0),

    CONSTRAINT CHK_ST_Type
        CHECK (
            transaction_type IN (
                'PURCHASE',
                'SALE',
                'RETURN_IN',
                'RETURN_OUT',
                'ADJUSTMENT',
                'TRANSFER_IN',
                'TRANSFER_OUT'
            )
        )
);

-- =======================================================
-- 4. Purchase Management
-- =======================================================
CREATE TABLE purchase_headers (
    purchase_id    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    supplier_id    NUMBER NOT NULL,
    warehouse_id   NUMBER NOT NULL,
    purchase_date  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    invoice_no     VARCHAR2(100),
    total_amount   NUMBER(12,2) DEFAULT 0 NOT NULL,
    status         VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at     TIMESTAMP,

    CONSTRAINT PK_Purchase_Headers PRIMARY KEY (purchase_id),
    CONSTRAINT FK_PH_Supplier
        FOREIGN KEY (supplier_id)
        REFERENCES suppliers(supplier_id),
    CONSTRAINT FK_PH_Warehouse
        FOREIGN KEY (warehouse_id)
        REFERENCES warehouses(warehouse_id),
    CONSTRAINT UK_PH_Invoice_No UNIQUE (invoice_no),
    CONSTRAINT CHK_PH_Status CHECK (status IN ('DRAFT', 'CONFIRMED', 'CANCELLED')),
    CONSTRAINT CHK_PH_Total CHECK (total_amount >= 0)
);

CREATE TABLE purchase_lines (
    purchase_line_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    purchase_id      NUMBER NOT NULL,
    product_id       NUMBER NOT NULL,
    quantity         NUMBER NOT NULL,
    unit_cost        NUMBER(12,2) NOT NULL,
    line_total       NUMBER(12,2) NOT NULL,
    created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_Purchase_Lines PRIMARY KEY (purchase_line_id),
    CONSTRAINT FK_PL_Purchase
        FOREIGN KEY (purchase_id)
        REFERENCES purchase_headers(purchase_id),
    CONSTRAINT FK_PL_Product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id),
    CONSTRAINT CHK_PL_Quantity CHECK (quantity > 0),
    CONSTRAINT CHK_PL_Unit_Cost CHECK (unit_cost >= 0),
    CONSTRAINT CHK_PL_Line_Total CHECK (line_total >= 0)
);

-- =======================================================
-- 5. Sales Management
-- =======================================================
-----------------------------------------------------------
-- Create Sales Headers Table
-----------------------------------------------------------
CREATE TABLE sales_headers (
    sales_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    buyer_id      NUMBER NOT NULL,
    warehouse_id  NUMBER NOT NULL,
    sales_date    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    invoice_no    VARCHAR2(100),
    total_amount  NUMBER(12,2) DEFAULT 0 NOT NULL,
    status        VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at    TIMESTAMP,

    CONSTRAINT PK_Sales_Headers PRIMARY KEY (sales_id),
    CONSTRAINT FK_SH_Buyer
        FOREIGN KEY (buyer_id)
        REFERENCES buyers(buyer_id),
    CONSTRAINT FK_SH_Warehouse
        FOREIGN KEY (warehouse_id)
        REFERENCES warehouses(warehouse_id),
    CONSTRAINT UK_SH_Invoice_No UNIQUE (invoice_no),
    CONSTRAINT CHK_SH_Status CHECK (status IN ('DRAFT', 'CONFIRMED', 'CANCELLED')),
    CONSTRAINT CHK_SH_Total CHECK (total_amount >= 0)
);

-----------------------------------------------------------
-- Create Sales Lines Table
-----------------------------------------------------------
CREATE TABLE sales_lines (
    sales_line_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    sales_id      NUMBER NOT NULL,
    product_id    NUMBER NOT NULL,
    quantity      NUMBER NOT NULL,
    unit_price    NUMBER(12,2) NOT NULL,
    line_total    NUMBER(12,2) NOT NULL,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_Sales_Lines PRIMARY KEY (sales_line_id),
    CONSTRAINT FK_SL_Sales
        FOREIGN KEY (sales_id)
        REFERENCES sales_headers(sales_id),
    CONSTRAINT FK_SL_Product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id),
    CONSTRAINT CHK_SL_Quantity CHECK (quantity > 0),
    CONSTRAINT CHK_SL_Unit_Price CHECK (unit_price >= 0),
    CONSTRAINT CHK_SL_Line_Total CHECK (line_total >= 0)
);

-- =======================================================
-- 6. Security (Later)
-- =======================================================

-- =======================================================
-- 7. Audit (Later)
-- =======================================================

